import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav style={{ padding: "12px", borderBottom: "1px solid #eee", display: "flex", gap: 12 }}>
          <Link href="/">Home</Link>
          <Link href="/employee/">Employee</Link>
          <Link href="/boss/">Boss</Link>
          <Link href="/developer/">Developer</Link>
        </nav>
        <main style={{ padding: "16px" }}>{children}</main>
      </body>
    </html>
  );
}
