server:
  port: 8080
  servlet:
    context-path: /web_tools/salary_tool

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/salary_system}
    username: ${SPRING_DATASOURCE_USERNAME:salary_user}
    password: ${SPRING_DATASOURCE_PASSWORD:salary_pass123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${SPRING_MAIL_USERNAME:p61415@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: "${JWT_SECRET:mySecretKey}"
  expiration: "${JWT_EXPIRATION:86400000}" # 24 hours

tempToken:
  expirationSeconds: ${TEMP_TOKEN_EXPIRATION_SECONDS:600}

logging:
  level:
    com.salary: DEBUG
    org.springframework.security: DEBUG
